### ISSUE TITLE
Ядро не работет

### ISSUE THREAD

**Issue by vustur** [OpenGDPS/core-javascript#1]
![image](https://github.com/OpenGDPS/core-javascript/assets/102847236/ae069905-1d9d-4a06-996d-13fd298c4edf)

**Comment by DragonFire1230** [comment]
1.репортить баги [сюда](https://github.com/OpenGDPS/core/issues)
2.если ты про оффициальный сервак opengdps на своём ядре, он давно лежит
3.уровни не полностью реализованы, в данный момент там мост между оффициал Geometry Dash, ты можешь закоментировать некоторые строчки в routes/levels/get_levels.py, и в main.py в методе download_level

(ух блять сколько символов уже)

**Comment by vustur** [comment]
бляяя ну это была шутка прикол типа файлов нема и гдпс не работает
